### ISSUE TITLE
Time out issue when browsing endpoint (Running in IoT Edge)

### ISSUE THREAD

**Issue by ryan-ms** [Azure/azure-iiot-opc-twin-module#16]
Hi, I followed the instruction [here]( https://docs.microsoft.com/en-us/azure/iot-accelerators/howto-opc-twin-deploy-modules) to deploy the opc-twin module in IoT edge.

And I can successfully discover my OPC UA server, and find endpoint, but when I started to browse node, the OPC-twin module shows error as below.

[09:32:16 DBG] uat4600fc959c1d15666910d6166ef5c0f76203de0d twin starting...
[09:32:16 DBG] Starting Module Host...
[09:32:16 INF] Running in iotedge production context.
[09:32:17 INF] Module moxagateway_opctwin connection status changed to Connected due to Connection_Ok.
[09:32:17 INF] Module moxagateway_opctwin connection status changed to Disconnected_Retrying due to Communication_Error.
[09:32:17 INF] Module moxagateway_opctwin connection status changed to Disconnected_Retrying due to Communication_Error.
[09:32:17 INF] Module moxagateway_opctwin connection status changed to Connected due to Connection_Ok.
[09:32:17 ERR] Error #1 in twin host - restarting...
System.TimeoutException: The operation timed out. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.RoundTripTwinMessage(AmqpMessage amqpMessage, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.SendTwinGetAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass27_0.<<SendTwinGetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendTwinGetAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.GetTwinAsync()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost.StartAsync(String type, String siteId, String serviceInfo, IProcessControl reset)
   at Microsoft.Azure.IIoT.OpcUa.Edge.Supervisor.SupervisorServices.TwinHost.RunAsync()

![擷取](https://user-images.githubusercontent.com/29178018/61119230-ee4fc680-a4cc-11e9-9aed-d26b016b27b1.JPG)

But It will not happen while I run the twin-module via docker-compose.
Do you have any idea to slove the problem? thank you.

**Comment by karok2m** [comment]
Hello @ryan-ms. Thank you for reporting the issue. Can you please provide some additional details about your setup so that it is easier to reproduce the issue, such as:

- What operating system (including version) are you running IoT edge on ? If it is Windows, are you using Windows or Linux containers (via Docker) as container engine for IoT Edge ?
- In Azure portal, how does your Create Options look like in IoT Edge Custom Module dialog ?
- Which OPC UA server are you connecting to ?

Thanks, Karapet.

**Comment by ryan-ms** [comment]
Hi karok2m, 

Thanks for your reply. I will provide more detail.

My architecture is just like the picture below.
![擷取222](https://user-images.githubusercontent.com/29178018/61264250-77614900-a7be-11e9-8103-4fdcdbd17f0f.JPG)

And below are my configuration on Azure portal:

ImageUri of OPC twin :
`mcr.microsoft.com/iotedge/opc-twin:latest`

Create option of opc twin :
`{
  "NetworkingConfig": {
    "EndpointsConfig": {
      "host": {}
    }
  },
  "HostConfig": {
    "NetworkMode": "host",
    "CapAdd": [
      "NET_ADMIN"
    ]
  }
}`

ImageUri of OPC Publisher :
`mcr.microsoft.com/iotedge/opc-publisher:latest`

Create option of OPC Publisher :
`{
  "Hostname": "publisher",
  "Cmd": [
    "publisher",
    "--pf=./pn.json",
    "--di=60",
    "--to",
    "--aa",
    "--si=0",
    "--ms=0"
  ],
  "ExposedPorts": {
    "62222/tcp": {}
  },
  "NetworkingConfig": {
    "EndpointsConfig": {
      "host": {}
    }
  },
  "HostConfig": {
    "NetworkMode": "host",
    "PortBindings": {
      "62222/tcp": [
        {
          "HostPort": "62222"
        }
      ]
    }
  }
}`

And the routing setting is
`{
  "routes": {
    "opctwinToIoTHub": "FROM /messages/modules/opctwin/* INTO $upstream",
    "opcpublisherToIoTHub": "FROM /messages/modules/opcpublisher/* INTO $upstream"
  }
}`

And to perform node browsing action, I used the connected factory UI to click "browse nodes" like below.
![123](https://user-images.githubusercontent.com/29178018/61263800-d32ad280-a7bc-11e9-8bb5-869cf013f654.jpg)

And then the error occurred. The UI shows error.
![bbbb](https://user-images.githubusercontent.com/29178018/61263852-ff465380-a7bc-11e9-9186-8d1db6c108d5.jpg)

And in the same time, the log of OPC twin module shows communication error as below which I mentioned in previous post.

`[09:32:16 DBG] uat4600fc959c1d15666910d6166ef5c0f76203de0d twin starting...
[09:32:16 DBG] Starting Module Host...
[09:32:16 INF] Running in iotedge production context.
[09:32:17 INF] Module moxagateway_opctwin connection status changed to Connected due to Connection_Ok.
[09:32:17 INF] Module moxagateway_opctwin connection status changed to Disconnected_Retrying due to Communication_Error.
[09:32:17 INF] Module moxagateway_opctwin connection status changed to Disconnected_Retrying due to Communication_Error.
[09:32:17 INF] Module moxagateway_opctwin connection status changed to Connected due to Connection_Ok.
[09:32:17 ERR] Error #1 in twin host - restarting...
System.TimeoutException: The operation timed out. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.RoundTripTwinMessage(AmqpMessage amqpMessage, CancellationToken cancellationToken)
at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.SendTwinGetAsync(CancellationToken cancellationToken)
at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func 1 asyncOperation)
at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass27_0.<b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendTwinGetAsync(CancellationToken cancellationToken)
at Microsoft.Azure.Devices.Client.InternalClient.GetTwinAsync()
--- End of inner exception stack trace ---
at Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost.StartAsync(String type, String siteId, String serviceInfo, IProcessControl reset)
at Microsoft.Azure.IIoT.OpcUa.Edge.Supervisor.SupervisorServices.TwinHost.RunAsync()
`
If you need more detail, or if the information is not clear enough, please let me know. Thank you.

**Comment by tbn-mm** [comment]
Duplicate of #6

**Comment by karok2m** [comment]
Hi @ryan-ms. Thank you for the details of the setup. I was able to reproduce the issue locally with a similar environment. And I found out that this is caused by a known issue in `opctwin` module. The issue is already fixed in `develop` branch. Unfortunately the fix is not yet merged in the `master` branch, so it is not published as a docker image just yet. The merge should happen in the end of this moth, so the image will be available on the official Microsoft container registry then.

If you require the fix now, what you can do is checkout `develop` branch and follow the instructions on [Build, run and deploy the module to IoT Edge (Production)](https://github.com/Azure/azure-iiot-opc-twin-module/tree/develop#build-run-and-deploy-the-module-to-iot-edge-production).

**Comment by ryan-ms** [comment]
Hi @karok2m. Thanks for your reply.
So I built it the image from `develop` branch, and the issue seems be resolved. Thanks a lot
But after that there is another issue seems related to certificate.

`[03:11:20 DBG] Creating new session to opc.tcp://192.168.4.101:4840/...
[03:11:20 WRN] Using unsecure connection.
[03:11:20 INF] Creating session to opc.tcp://192.168.4.101:4840/ via opc.tcp://192.168.4.101:4840/.
[03:11:20 ERR] (Error) Certificate 'O=Siemens, C=DE, CN=PLC-1/OPCUA-1-5' rejected. Reason=BadCertificateUntrusted
[03:11:20 ERR] (Error) Writing rejected certificate to directory: [Directory]pki/rejected
[03:11:20 DBG] Failed to create session to opc.tcp://192.168.4.101:4840/ - retry.
Opc.Ua.ServiceResultException: Certificate issuer is not trusted.
SubjectName: O=Siemens, C=DE, CN=PLC-1/OPCUA-1-5
IssuerName: O=Siemens, C=DE, CN=Siemens TIA Project(ZQwELMpVgUiyOdYiAJm-Ug) ---> Opc.Ua.ServiceResultException: Certificate issuer is not trusted.
SubjectName: O=Siemens, C=DE, CN=PLC-1/OPCUA-1-5
IssuerName: O=Siemens, C=DE, CN=Siemens TIA Project(ZQwELMpVgUiyOdYiAJm-Ug)
   at Opc.Ua.CertificateValidator.InternalValidate(X509Certificate2Collection certificates)
   --- End of inner exception stack trace ---
   at Opc.Ua.Client.Session.Create(ApplicationConfiguration configuration, ConfiguredEndpoint endpoint, Boolean updateBeforeConnect, Boolean checkDomain, String sessionName, UInt32 sessionTimeout, IUserIdentity identity, IList 1 preferredLocales)
   at Microsoft.Azure.IIoT.OpcUa.Protocol.Services.ClientSession.CreateSessionAsync(IUserIdentity identity)
   at Microsoft.Azure.IIoT.OpcUa.Protocol.Services.ClientSession.RunAsync()
[03:11:20 DBG] BadCertificateUntrusted => NoTrust
[03:11:20 DBG] Try to connect to opc.tcp://192.168.4.101:4840/ in 67252 ms...
`
Do you have any idea for this situation?

**Comment by tbn-mm** [comment]
> Do you have any idea for this situation?

Add "AutoAccept=true" to cmd

**Comment by ryan-ms** [comment]
> > 
> 
> Add "AutoAccept=true" to cmd

Hi, @tbn-mm 

It work! Thanks a lot.
So it's like an OPC UA client auto trust the OPC UA server's certificate, right?!

Do OPC Twin have the mechanism which can read certificate in trust folder and put the untrusted certificated in reject folder? If so, how do we configure that in create option?

Thank you.

**Comment by karok2m** [comment]
Hi @ryan-ms. Correct, with `AutoAccept=true` Twin module will accept any certificate provided by an OPC UA Server.

So, there are a few parameters similar to `AutoAccept`  that you can use,  but they are still only in `develop` branch and are not documented yet. Similar parameters exist for OPC Publisher module, so please have a look at [Command line options](https://github.com/Azure/iot-edge-opc-publisher#command-line-options) of OPC Publisher if you need more details. Also, please make sure to check the [OPC UA X.509 certificates](https://github.com/Azure/iot-edge-opc-publisher#opc-ua-x509-certificates) part of OPC Publisher documentation for details of certificate management.

Here are the parameters of OPC Twin module:

- **`AutoAccept`**: the publisher trusts all servers it is a connection to
  - default: `false`

- **`AppCertStoreType`**: the own application cert store type
  - allowed values: `X509Store` for `Windows`, `Directory` for `Linux`
  - default: `X509Store` on `Windows`, and `Directory` on `Linux`

- **`PkiRootPath`**: PKI Certificate root path
  - default: `pki`

- **`OwnCertPath`**: the path where the own application cert should be stored
  - default: value of `PkiRootPath` + `/own`

- **`TrustedCertPath`**: the path of the trusted cert store
  - default: value of `PkiRootPath` + `/trusted`

- **`IssuerCertPath`**: the path of the trusted issuer cert store
  - default: value of `PkiRootPath` + `/issuer`

- **`RejectedCertPath`**: the path of the rejected cert store
  - default: value of `PkiRootPath` + `/rejected`

- **`OwnCertX509StorePathDefault`**:
  - default: `CurrentUser\\UA_MachineDefault`

If you wan to provide your own trusted certificates, then what you can do is have a `pki` directory with similar structure as described above (with `own`, `trusted`, `issuer` and `rejected` sub-directories) on your host filesystem, mount it somewhere into the OPC Twin module container and specify `PkiRootPath` to point to the mounted directory.

To mount a directory from host filesystem to the container add `Binds` part to `HostConfig` in the `Container Create Options` of the module. In the bellow case we mount `/host_mnt/mnt/mount` directory of host filesystem as `/mount` directory in the container.

```
{
  ...
  "HostConfig": {
    "Binds": [
      "/host_mnt/mnt/mount:/mount"
    ]
  }
}
```
