### ISSUE TITLE
Error during module execution inside IoT Edge

### ISSUE THREAD

**Issue by tbn-mm** [Azure/azure-iiot-opc-twin-module#5]
I tried to run the module inside IoT Edge without the EdgeHubConnectionString as argument, but I get the following exception:

```
[11:28:46 DBG] Starting Module Host...
[11:28:46 ERR] Error during module execution - restarting!
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory.ModuleClientAdapter.<>c__DisplayClass5_0.<CreateAsync>b__0(ConnectionStatus s, ConnectionStatusChangeReason r)
   at Microsoft.Azure.Devices.Client.InternalClient.OnConnectionStatusChanged(ConnectionStatus status, ConnectionStatusChangeReason reason)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass35_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory.ModuleClientAdapter.CreateAsync(String product, IotHubConnectionStringBuilder cs, ITransportSettings transportSetting, TimeSpan timeout, IRetryPolicy retry, Action onConnectionLost, ILogger logger)
   at Microsoft.Azure.IIoT.Utils.Try.Options[T](Func`1[] options)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost.StartAsync(String type, String siteId, String serviceInfo, IProcessControl reset)
   at Microsoft.Azure.IIoT.Modules.OpcUa.Twin.ModuleProcess.RunAsync() in /src/src/ModuleProcess.cs:line 93
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory.ModuleClientAdapter.<>c__DisplayClass5_0.<CreateAsync>b__0(ConnectionStatus s, ConnectionStatusChangeReason r)
   at Microsoft.Azure.Devices.Client.InternalClient.OnConnectionStatusChanged(ConnectionStatus status, ConnectionStatusChangeReason reason)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass35_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Microsoft.Azure.IIoT.Module.Framework.Client.IoTSdkFactory.ModuleClientAdapter.CreateAsync(String product, IotHubConnectionStringBuilder cs, ITransportSettings transportSetting, TimeSpan timeout, IRetryPolicy retry, Action onConnectionLost, ILogger logger)
   at Microsoft.Azure.IIoT.Utils.Try.Options[T](Func`1[] options)<---

```

It's running on Linux amd64 and the latest mschier_develop (master or tag 2.0.0 doesn't compile: 'LogEx' does not contain a definition for 'Level'). It's running when I set cmd EdgeHubConnectionString (which is the module connection string, not edgehub)

**Comment by marcschier** [comment]
Hi @tbn-mm, our nightly build succeeded and I just tried as well, and also do not have an issue in master.  However, I had similar issues happen to me where I had bad nugets in my package cache, e.g. from building the nugets myself, rather than pulling from nuget.org.  First make sure you pulled the latest from master, then in your home folder there should be a .nuget\packages folder.  Delete all Microsoft.Azure.IIoT* packages and then do a restore and build.  That should work.  

Regarding the exception, I will look into it.  Could you share your deployment.json file, at least the edge* and twin/publisher module configuration?  Or at minimum, which image and version you deployed?  Thanks a lot.

**Comment by marcschier** [comment]
Hi @tbn-mm, indeed we have a bug when running the module in the IoTEdge context.  This does not affect running the module standalone using the CLI host, which explains why the simulation deployment worked.   This will be fixed in 2.0.1, which will be released today or tomorrow.

**Comment by tbn-mm** [comment]
> our nightly build succeeded and I just tried as well, and also do not have an issue in master.
>
Found the problem: I'm using Docker to build the Twin module. The docker file [docker/linux/amd64/Dockerfile](https://github.com/Azure/azure-iiot-opc-twin-module/blob/master/docker/linux/amd64/Dockerfile) is using dotnet 2.1, that doesn't work. Dotnet 2.2 is required.

> Could you share your deployment.json file, at least the edge* and twin/publisher module configuration? Or at minimum, which image and version you deployed? Thanks a lot.
>

deployment.json:
```
"modules": {
	"twin": {
		"type": "docker",
		"settings": {
			"image": "tbn.azurecr.io/twin",
			"createOptions": ""
		},
		"status": "running",
		"restartPolicy": "always",
		"version": "1.0"
	},
	"publisher": {
		"type": "docker",
		"settings": {
			"image": "mcr.microsoft.com/iotedge/opc-publisher",
			"createOptions": "{\"Hostname\":\"publisher\",\"Cmd\":[\"publisher\",\"--pf=./pn.json\",\"--di=60\",\"--to\",\"--aa\",\"--si=0\",\"--ms=0\"],\"ExposedPorts\":{\"62222/tcp\":{}},\"HostConfig\":{\"PortBindings\":{\"62222/tcp\":[{\"HostPort\":\"62222\"}]}}}"
		},
		"version": "1.0",
		"status": "running",
		"restartPolicy": "always"
	}
}
```
Another problem: If I add `"NetworkMode": "host"`, it won't start and edgeAgent says: `failed to add interface veth9f31b8c to sandbox: error setting interface "veth9f31b8c" IP to 172.18.0.3/16: cannot program address 172.18.0.3/16 in sandbox interface because it conflicts with existing route {Ifindex: 4 Dst: 172.18.0.0/16 Src: 172.18.0.1`
I also setup a fresh Ubuntu 18.04 installation, but this sandbox interface conflict still exists.
Image from `mcr.microsoft.com/iotedge/opc-twin` has the same behavior.

**Comment by marcschier** [comment]
Weird issue on the dotnet 2.2 part, I will poke into that as well, but our CI builds use the checked in dockerfile to build (and I used that also to validate the build errors).   

The twin repo root contains a deployment.json which I used to validate the bug.   I also found the issue with NetworkMode, which I am also following up with the IoT Edge team on as "host" mode should be supported on Linux, the workaround for now is to remove it, however, that is at the expense of not being able to sit in the host network, which limits the twin functionality.

**Comment by marcschier** [comment]
The network mode issue lies in the createOptions which should be
`"createOptions": "{\"NetworkingConfig\": {\"EndpointsConfig\": {\"host\": {}}}, \"HostConfig\": {\"NetworkMode\": \"host\" }}"`

**Comment by tbn-mm** [comment]
> Weird issue on the dotnet 2.2 part, I will poke into that as well
> 
My docker installation had to redownload the dotnet:2.1 image. Now it's compiling.

NetworkMode also works fine.

**Comment by tbn-mm** [comment]
It's now working. I'm closing it. Thanks.

**Comment by marcschier** [comment]
Thanks for closing - to give you an update - the 2.0.1 nugets are out, but the mcr images are still at 2.0.0 due to an issue in our ARM infrastructure, which will not be resolvable until Monday.  I hope then we are ready to also post the updated official images.   Until then I will re-opening to track.
