### ISSUE TITLE
endpoint activate causes twin module to restart

### ISSUE THREAD

**Issue by tbn-mm** [Azure/azure-iiot-opc-twin-module#6]
When using `/v2/endpoints/{endpointId}/activate` from Registry Service the twin module shows this message:

```
[13:34:14 ERR] Exception applying changes! Continue...
System.ArgumentNullException: Value cannot be null.
Parameter name: endpoint
   at Microsoft.Azure.IIoT.OpcUa.Protocol.Services.ClientServices.ExecuteServiceAsync[T](EndpointModel endpoint, CredentialModel elevation, Int32 priority, Func`2 service, Nullable`1 timeout, CancellationToken ct, Func`2 handler)
   at Microsoft.Azure.IIoT.OpcUa.Protocol.EndpointServicesEx.ExecuteServiceAsync[T](IEndpointServices client, EndpointModel endpoint, CredentialModel elevation, TimeSpan timeout, Func`2 service)
   at Microsoft.Azure.IIoT.Modules.OpcUa.Twin.v2.Supervisor.NodeSettingsController.WriteAsync(String nodeId, JToken value) in /src/src/v2/Controllers/NodeSettingsController.cs:line 96
   at Microsoft.Azure.IIoT.Modules.OpcUa.Twin.v2.Supervisor.NodeSettingsController.ApplyAsync() in /src/src/v2/Controllers/NodeSettingsController.cs:line 80
   at Microsoft.Azure.IIoT.Module.Framework.Hosting.SettingsRouter.Controller.SafeApplyAsync()
[13:34:14 DBG] Applying new settings took 00:00:00.0009411...
```

Registry Service is created today from master using the deploy.cmd from azure-iiot-components.
The Twin module is self built: `docker build -f docker/linux/amd64/Dockerfile -t tbn.azurecr.io/twin6 azure-iiot-opc-twin-module-master` from todays master branch and it's running on an IoTEdge device.

deployment.json:
```
"modules": {
	"publisher": {
		"type": "docker",
		"settings": {
			"image": "mcr.microsoft.com/iotedge/opc-publisher:latest",
			"createOptions": "{\"Hostname\":\"publisher\",\"Cmd\":[\"publisher\",\"--pf=./pn.json\",\"--di=60\",\"--to\",\"--aa\",\"--si=0\",\"--ms=0\"],\"ExposedPorts\":{\"62222/tcp\":{}},\"HostConfig\":{\"PortBindings\":{\"62222/tcp\":[{\"HostPort\":\"62222\"}]}}}"
		},
		"version": "1.0",
		"status": "running",
		"restartPolicy": "always"
	},
	"twin": {
		"type": "docker",
		"settings": {
			"image": "tbn.azurecr.io/twin6",
			"createOptions": "{\"NetworkingConfig\":{\"EndpointsConfig\":{\"host\":{}}},\"HostConfig\":{\"NetworkMode\":\"host\"}}"
		},
		"version": "1.0",
		"status": "running",
		"restartPolicy": "always"
	}
}
```

**Comment by marcschier** [comment]
Hi @tbn-mm, nice find and thank you for reporting this issue!  I am not reproducing this using the CLI - what I am doing:

- Put module into discovery mode (supervisors update -i <id> -d Fast)
- Once onboarded - activate all endpoints (endpoints activate)
- List all connected and ready to use endpoints (endpoints query -s Ready)
- Browse (nodes browse -i <endpointid> -r
- Unregister all (apps unregister)

To make sure that there are no "double" activation issues, I also ran activate twice on some endpoint, and in quick succession activate and deactivate.

However, what you are seeing is indeed incorrect behavior.  The node settings controller should not be involved during activation - it is a controller for the endpoint twin, so my assumption is that there are bad / unknown properties in the endpoint device twin that trigger this behavior.  That said, the controller should manage the exception and continue executing, the module should not restart (unless it also lost connection to the hub).

It would be awesome if you could provide me with a concrete repro, e.g. what you needed to do to get into this state.  Also - what would be great if you could a) get me the content of the device twin with the used "endpointId" (it is the device id of the iot hub device) and b) get me the log part where the twin module is restarting.  Also, is the module, and furthmore the endpoint usable after the restart?

Thanks a lot!

**Comment by tbn-mm** [comment]
`/v2/applications/discover` POST 
```
{
  "discovery": "Network",
  "configuration": {
    "addressRangesToScan": "192.168.2.0/24",
    "activationFilter": {
      "securityMode": "None"
    }
  }
}
```

then `/v2/endpoints` shows 

```
...
{
      "registration": {
        "id": "uat3da64f1032fd291c53ef181e823ab97f4339d352",
        "endpointUrl": "opc.tcp://PFC-SYSO-117:4840",
        "endpoint": {
          "url": "opc.tcp://192.168.2.117:4840/",
          "alternativeUrls": [
            "opc.tcp://192.168.2.117:4840/",
            "opc.tcp://PFC-SYSO-117:4840"
          ],
          "user": {},
          "securityMode": "None",
...
```

So I do `endpoints activate -i uat3da64f1032fd291c53ef181e823ab97f4339d352`
and then this huge message appears:
```
[15:30:57 DBG] uat3da64f1032fd291c53ef181e823ab97f4339d352 twin starting...
[15:30:57 DBG] Starting Module Host...
[15:30:57 INF] Running in iotedge production context.
[15:30:57 INF] Module ubuntu2_twin connection status changed to Disconnected_Retrying due to Communication_Error.
[15:30:57 INF] Module ubuntu2_twin connection status changed to Connected due to Connection_Ok.
[15:30:57 INF] Module ubuntu2_twin connection status changed to Disconnected_Retrying due to Communication_Error.
[15:30:57 INF] Initialize twin for ubuntu2 - twin
[15:30:57 DBG] Applying initial state.
[15:30:57 ERR] Exception applying changes! Continue...
System.ArgumentNullException: Value cannot be null.
Parameter name: endpoint
   at Microsoft.Azure.IIoT.OpcUa.Protocol.Services.ClientServices.ExecuteServiceAsync[T](EndpointModel endpoint, CredentialModel elevation, Int32 priority, Func`2 service, Nullable`1 timeout, CancellationToken ct, Func`2 handler)
   at Microsoft.Azure.IIoT.OpcUa.Protocol.EndpointServicesEx.ExecuteServiceAsync[T](IEndpointServices client, EndpointModel endpoint, CredentialModel elevation, TimeSpan timeout, Func`2 service)
   at Microsoft.Azure.IIoT.Modules.OpcUa.Twin.v2.Supervisor.NodeSettingsController.WriteAsync(String nodeId, JToken value) in /src/src/v2/Controllers/NodeSettingsController.cs:line 96
   at Microsoft.Azure.IIoT.Modules.OpcUa.Twin.v2.Supervisor.NodeSettingsController.ApplyAsync() in /src/src/v2/Controllers/NodeSettingsController.cs:line 80
   at Microsoft.Azure.IIoT.Module.Framework.Hosting.SettingsRouter.Controller.SafeApplyAsync()
[15:30:57 DBG] Applying new settings took 00:00:00.0011323...
[15:30:57 INF] Module ubuntu2_twin connection status changed to Connected due to Connection_Ok.
[15:30:57 INF] Module ubuntu2_twin connection status changed to Disconnected_Retrying due to Communication_Error.
[15:30:57 INF] Module ubuntu2_twin connection status changed to Connected due to Connection_Ok.
[15:30:57 INF] Module ubuntu2_twin connection status changed to Disconnected_Retrying due to Communication_Error.
[15:30:57 ERR] Error #1 in twin host - restarting...
System.TimeoutException: The operation timed out. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendTwinPatchAsync(TwinCollection reportedProperties, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.UpdateReportedPropertiesAsync(TwinCollection reportedProperties)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost.StartAsync(String type, String siteId, String serviceInfo, IProcessControl reset)
   at Microsoft.Azure.IIoT.OpcUa.Edge.Supervisor.SupervisorServices.TwinHost.RunAsync()
[15:30:57 INF] uat3da64f1032fd291c53ef181e823ab97f4339d352 twin started.
[15:30:57 DBG] Starting Module Host...
[15:30:57 INF] Running in iotedge production context.
[15:30:57 INF] Module ubuntu2_twin connection status changed to Connected due to Connection_Ok.
[15:30:57 INF] Module ubuntu2_twin connection status changed to Disconnected_Retrying due to Communication_Error.
[15:30:58 INF] Module ubuntu2_twin connection status changed to Connected due to Connection_Ok.
[15:30:58 INF] Module ubuntu2_twin connection status changed to Disconnected_Retrying due to Communication_Error.
[15:30:58 INF] Module ubuntu2_twin connection status changed to Connected due to Connection_Ok.
[15:30:58 INF] Module ubuntu2_twin connection status changed to Disconnected_Retrying due to Communication_Error.
[15:30:58 INF] Module ubuntu2_twin connection status changed to Connected due to Connection_Ok.
[15:31:03 ERR] Error #2 in twin host - restarting...
System.TimeoutException: The operation timed out. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.RoundTripTwinMessage(AmqpMessage amqpMessage, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.SendTwinGetAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass27_0.<<SendTwinGetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendTwinGetAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.GetTwinAsync()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost.StartAsync(String type, String siteId, String serviceInfo, IProcessControl reset)
   at Microsoft.Azure.IIoT.OpcUa.Edge.Supervisor.SupervisorServices.TwinHost.RunAsync()
[15:31:03 DBG] Starting Module Host...
[15:31:03 INF] Running in iotedge production context.
[15:31:03 INF] Module ubuntu2_twin connection status changed to Disconnected_Retrying due to Communication_Error.
[15:31:03 INF] Module ubuntu2_twin connection status changed to Connected due to Connection_Ok.
[15:31:03 INF] Module ubuntu2_twin connection status changed to Disconnected_Retrying due to Communication_Error.
[15:31:03 INF] Module ubuntu2_twin connection status changed to Connected due to Connection_Ok.
[15:31:03 INF] Module ubuntu2_twin connection status changed to Disconnected_Retrying due to Communication_Error.
[15:31:03 INF] Module ubuntu2_twin connection status changed to Connected due to Connection_Ok.
[15:31:13 ERR] Error #3 in twin host - restarting...
System.TimeoutException: The operation timed out. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.RoundTripTwinMessage(AmqpMessage amqpMessage, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.AmqpTransportHandler.SendTwinGetAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass27_0.<<SendTwinGetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendTwinGetAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.GetTwinAsync()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost.StartAsync(String type, String siteId, String serviceInfo, IProcessControl reset)
   at Microsoft.Azure.IIoT.OpcUa.Edge.Supervisor.SupervisorServices.TwinHost.RunAsync()
[15:31:13 DBG] Starting Module Host...
[15:31:13 INF] Running in iotedge production context.
[15:31:13 INF] Module ubuntu2_twin connection status changed to Disconnected_Retrying due to Communication_Error.
[15:31:13 INF] Module ubuntu2_twin connection status changed to Connected due to Connection_Ok.
[15:31:13 INF] Initialize twin for ubuntu2 - twin
[15:31:13 DBG] Applying initial state.
[15:31:13 ERR] Exception applying changes! Continue...
System.ArgumentNullException: Value cannot be null.
Parameter name: endpoint
   at Microsoft.Azure.IIoT.OpcUa.Protocol.Services.ClientServices.ExecuteServiceAsync[T](EndpointModel endpoint, CredentialModel elevation, Int32 priority, Func`2 service, Nullable`1 timeout, CancellationToken ct, Func`2 handler)
   at Microsoft.Azure.IIoT.OpcUa.Protocol.EndpointServicesEx.ExecuteServiceAsync[T](IEndpointServices client, EndpointModel endpoint, CredentialModel elevation, TimeSpan timeout, Func`2 service)
   at Microsoft.Azure.IIoT.Modules.OpcUa.Twin.v2.Supervisor.NodeSettingsController.WriteAsync(String nodeId, JToken value) in /src/src/v2/Controllers/NodeSettingsController.cs:line 96
   at Microsoft.Azure.IIoT.Modules.OpcUa.Twin.v2.Supervisor.NodeSettingsController.ApplyAsync() in /src/src/v2/Controllers/NodeSettingsController.cs:line 80
   at Microsoft.Azure.IIoT.Module.Framework.Hosting.SettingsRouter.Controller.SafeApplyAsync()
[15:31:13 DBG] Applying new settings took 00:00:00.0011959...
[15:31:13 INF] Module ubuntu2_twin connection status changed to Disconnected_Retrying due to Communication_Error.
[15:31:13 INF] Module ubuntu2_twin connection status changed to Connected due to Connection_Ok.
[15:31:13 INF] Module ubuntu2_twin connection status changed to Disconnected_Retrying due to Communication_Error.
[15:31:13 INF] Module ubuntu2_twin connection status changed to Connected due to Connection_Ok.
[15:31:27 DBG] uat3da64f1032fd291c53ef181e823ab97f4339d352 twin is stopped...
[15:31:27 INF] uat3da64f1032fd291c53ef181e823ab97f4339d352 twin stopped.
```
(this takes a minute, see time)
After that, I get `System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
` from the CLI console. The endpoint is still deactivated. The module is usable (can start a second discovery or can do the same command again).

**Comment by tbn-mm** [comment]
I just found out that this issue only appears when the module runs on an IotEdge device.

**Comment by mma-mm** [comment]
I can observe this issue too.
