### ISSUE TITLE
azure-iiot-opc-twin-module stops responding to requests

### ISSUE THREAD

**Issue by mma-mm** [Azure/azure-iiot-opc-twin-module#7]
Hi,

i'm using the opc-twin-module to browse an opc-server from another edge module using the supervisorclient of azure-iiot-opc-ua. 
Sometimes the opc twin module stops responding to direct method calls, so an IoTHubException is thrown:

    Microsoft.Azure.Devices.Client.Exceptions.IotHubException: {"message":"Timed out waiting for device to respond to method request 9aabd6bb-d1a9-47ac-833f-ac040cb53b5f","exceptionMessage":"","status":0,"payload":null}
       at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.ExecuteAsync(HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`2 isSuccessful, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)
       at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.PostAsync[T1,T2](Uri requestUri, T1 entity, IDictionary`2 errorMappingOverrides, IDictionary`2 customHeaders, CancellationToken cancellationToken)
       at Microsoft.Azure.Devices.Client.ModuleClient.InvokeMethodAsync(Uri uri, MethodRequest methodRequest, CancellationToken cancellationToken)
       at Microsoft.Azure.IIoT.Module.Framework.Hosting.ModuleHost.CallMethodAsync(String deviceId, String moduleId, String method, String payload, Nullable`1 timeout)
       at Microsoft.Azure.IIoT.Module.Default.ChunkMethodClient.CallMethodAsync(String deviceId, String moduleId, String method, Byte[] payload, String contentType, Nullable`1 timeout)
       at Microsoft.Azure.IIoT.Module.MethodClientEx.CallMethodAsync(IMethodClient client, String deviceId, String moduleId, String method, String json, Nullable`1 timeout)
       at Microsoft.Azure.IIoT.OpcUa.Twin.Clients.SupervisorClient.CallServiceOnSupervisor[T,R](String service, EndpointRegistrationModel registration, T request)
       at Microsoft.Azure.IIoT.OpcUa.Twin.Clients.SupervisorClient.NodeValueReadAsync(EndpointRegistrationModel registration, ValueReadRequestModel request)
       at MyModule.Communication.Twincommunicator.GetValue(String nodeId)

This is the same issue as [this one](https://github.com/Azure/azure-iiot-opc-ua/issues/5), the root cause seems to be in the opc-twin-module.

**Comment by marcschier** [comment]
Hi Matthias, we will look into it.  Can you provide more information as to what version of IoT Edge you are using?  Thanks!

**Comment by mma-mm** [comment]
I'm using the default setting in the IoTHub. The image is from mcr.microsoft.com/azureiotedge-hub:1.0 .

**Comment by marcschier** [comment]
Thanks a lot @mma-mm.  We will then try with the latest version publicly available.
